
name: Build website

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the main branch
on:
  push:
    branches: [ main, master ]
  pull_request:
    types: [opened, synchronize, reopened, closed]
    branches: [ main, master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: windows-latest
    env:
      DOTNET_CLI_TELEMETRY_OPTOUT: 1
      DOTNET_SKIP_FIRST_TIME_EXPERIENCE: 1
      DOTNET_NOLOGO: true
      DOTNET_GENERATE_ASPNET_CERTIFICATE: false
      solutionpath: src\StatiqMermaid.Website.sln
      
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    - name: Verify the ref context
      run: echo 'Ref Context is ${{ github.ref }}'

    - name: Verify the head ref context
      run: echo 'Head Ref Context is ${{ github.head_ref }}'

    - name: Verify if release label exists
      run: echo 'Contains Release label ${{ contains(github.event.pull_request.labels.*.name, 'release') }}'

    - name: Verify the event name
      run: echo 'Event Name is ${{ github.event_name }}'

    - name: Verify the event action
      run: echo 'Head Event Action is ${{ github.event.action }}'

    - name: Verify if Pull Request merge
      run: echo 'Pull Request Merged is ${{ github.event.pull_request.merged }}'
      
    - uses: actions/setup-dotnet@v3
      name: Setup Dot Net 
      
    - name: Checkout 
      uses: actions/checkout@v3

    - name: NPM package restore
      run: |
        pushd src\StatiqMermaid.Website\
        npm install
        popd

    - name: Restore Packages
      run: |
        dotnet restore ${{ env.solutionpath }} /bl:artifacts\\binlog\\restore.binlog

    - name: Build Statiq
      run: |
        dotnet build ${{ env.solutionpath }} --configuration Release --no-restore /bl:artifacts\\binlog\\build.binlog /p:ContinuousIntegrationBuild=true
        

    - name: Build Website
      run: |
        pushd src\StatiqMermaid.Website\
        dotnet run -c Release
        popd
        
